version: "3.8"
services:
  db:
    image: mysql:8
    container_name: dewlist-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret_root_pw
      MYSQL_DATABASE: dewlist
      MYSQL_USER: dewuser
      MYSQL_PASSWORD: secret_pw
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
